---
title: "Biography"
output: html_document
showpagemeta: false
---

My name is Ryder Davis. I was born in San Antonio, and I moved to Austin when I was 5, and I have been here since. I graduated from Rouse High School and am currently attending the University of Texas at Austin. I enjoy watching and playing the majority of sports. In high school, I played golf and ultimate frisbee, two compldtely different sports. I also enjoy video games and listening to music. I've recently been interested in learning how to make electronic music. I currently have two jobs. One is an HEB cashier, which I've had since I turned 16. The other is a flag football referee, which is quite fun for a student job. In terms of skills, I am in the process of becoming fluent in Spanish, but I still have a ways to go. I'd rather not bore you with academic skills that everyone says that they have, so I'll only state the unique ones. I'm quite talented when it comes to punting a football. I have no actual in-game experience, but I can punt 60 yards fairly consistently. Another interesting skill is that I'm really good at ping pong. My biggest accomplishment so far has been graduating high school as the valedictorian and attending UT, but I hope for bigger things in my future.  My life hasn't been all that interesting so far, but I expect that to change after I graduate college.
